Models/Datos/Singleton.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BibliotecaGenerica;

namespace L1_TalentHub.Models.Datos
{
    public sealed class Singleton
    {
        private readonly static Singleton _instance = new Singleton();

        public List<Registros> ListaRegistros;
        public List<Registros> RegistrosEncontrados;
        public List<List<Registros>> ListaDeListas;
        public AVLRepetidos<Registros> AVLNombres;
        

        private Singleton()
        {
            ListaRegistros = new List<Registros>();
            RegistrosEncontrados = new List<Registros>();
            ListaDeListas = new List<List<Registros>>();
            AVLNombres = new AVLRepetidos<Registros>();

        }


        public static Singleton Instance
        {
            get
            {
                return _instance;
            }
        }
    }
}

Models/ErrorViewModel.cs
using System;

namespace L1_TalentHub.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Registros.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;


namespace L1_TalentHub.Models
{
    public class Registros: IComparable
    {
        [Required(ErrorMessage = "Rellene el campo del Nombre")]
        [Display(Name = "Nombre")]
        [JsonProperty(PropertyName = "name")]//Hacer coincidir los nombres del Json con las de la clase Registro
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Rellene el campo del DPI")]
        [Display(Name = "DPI")]
        [JsonProperty(PropertyName = "dpi")]//Hacer coincidir los nombres del Json con las de la clase Registro
        public string Dpi { get; set; }

        [Required(ErrorMessage = "Rellene el campo de la Fecha De Nacimiento")]
        [Display(Name = "Fecha De Nacimiento")]
        [JsonProperty(PropertyName = "datebirth")]//Hacer coincidir los nombres del Json con las de la clase Registro
        public string Nacimiento { get; set; }

        [Required(ErrorMessage = "Rellene el campo de la Dirección")]
        [Display(Name = "Dirección")]
        [JsonProperty(PropertyName = "address")]//Hacer coincidir los nombres del Json con las de la clase Registro
        public string Direccion { get; set; }

        [JsonIgnore]
        public Comparison<Registros> InsertarPorDPI = delegate (Registros registro1, Registros registro2)
        {
            return registro1.Dpi.CompareTo(registro2.Dpi);
        };
        
        [JsonIgnore]
        public Comparison<Registros> InsertarPorNombre = delegate (Registros registro1, Registros registro2)
        {
            return registro1.Nombre.CompareTo(registro2.Nombre);
        };


        public int CompareTo(object obj)
        {
            throw new NotImplementedException();
        }

    }
}

Controllers/TalenHubController.cs
using L1_TalentHub.Models;
using L1_TalentHub.Models.Datos;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IO;
using System.Linq;

namespace L1_TalentHub.Controllers
{
    public class TalenHubController : Controller
    {
        // GET: TalenHub
        public ActionResult Index()
        {           
            return View(Singleton.Instance.ListaRegistros);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LeeArchivo(IFormFile ArchivoCargado)
        {
            try
            {
                var Archivo = new StreamReader(ArchivoCargado.OpenReadStream());
                {
                    string info = Archivo.ReadToEnd();
                    foreach (string Fila in info.Split("\n"))
                    {
                        if (!(string.IsNullOrEmpty(Fila)))
                        {
                            string jsonAccion = Fila.Split(";")[0];
                            string jsonString = Fila.Split(";")[1];

                            Registros NuevoRegistro = JsonConvert.DeserializeObject<Registros>(jsonString);

                            if (jsonAccion == "INSERT")
                            {
                                Singleton.Instance.AVLNombres.Agregar(NuevoRegistro, NuevoRegistro.InsertarPorNombre);
                            }
                            else if (jsonAccion == "PATCH")
                            {
                                Singleton.Instance.AVLNombres.Actualizar(NuevoRegistro, NuevoRegistro.InsertarPorNombre, NuevoRegistro.InsertarPorDPI);
                            }
                            else
                            {
                                Singleton.Instance.AVLNombres.Borrar(NuevoRegistro, NuevoRegistro.InsertarPorNombre, NuevoRegistro.InsertarPorDPI);
                            }

                            Singleton.Instance.ListaRegistros.Add(NuevoRegistro);                          
                        }
                    }
                }
                TempData["Mensaje"] = "Los Datos han sido cargados correctamente";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Index");
            }
        }

        public ActionResult Buscar(string id)
        {
            try
            {
                Registros NuevoRegistro = new Registros
                {
                    Nombre = id
                };

                Singleton.Instance.RegistrosEncontrados = Singleton.Instance.AVLNombres.Busqueda(NuevoRegistro, NuevoRegistro.InsertarPorNombre);

                if (Singleton.Instance.RegistrosEncontrados == null)
                {
                    TempData["Mensaje"] = "La Persona No Existe o Coloco Mal Los Datos";
                    return RedirectToAction(nameof(Index));
                }
                
                //Se asegura que exista la carpeta en donde almacenara los resultados de las busquedas
                if (!Directory.Exists(@"outputs"))
                {
                    System.IO.Directory.CreateDirectory("outputs");
                }

                string ruta = @"outputs/" + Singleton.Instance.RegistrosEncontrados[0].Nombre + ".csv";//Nombre del archivo

                for (int i = 0; i < Singleton.Instance.RegistrosEncontrados.Count; i++)
                {
                    string json = JsonConvert.SerializeObject(Singleton.Instance.RegistrosEncontrados[i]) + "\n";
                    System.IO.File.AppendAllText(ruta, json);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                TempData["Mensaje"] = "Coloque Datos Para Buscar";
                return RedirectToAction(nameof(Index));
            }
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - L1_TalentHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="TalenHub" asp-action="Index">Talent Hub</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - L1_TalentHub - Herbert Emilio Alfaro Montes - Carnet: 1181320
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/TalenHub/Index.cshtml
@model IEnumerable<L1_TalentHub.Models.Registros>

@{
    ViewData["Title"] = "Index";
}

<h1>Talent Hub</h1>

<form asp-action="Buscar">
    <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Buscar</button>
    <p>

    </p>
    <input name="id" type="text" value="" class="form-control" />
</form>

<p>

</p>

<form method="post" enctype="multipart/form-data" asp-controller="TalenHub" asp-action="LeeArchivo">

    <input type="file" class="form-control-file" name="ArchivoCargado" />
    <br />
    <input type="submit" value="Agregar" class="form-file" />

</form>

<p>

</p>

<h3>
    <span style="color: red;">
        @TempData["Mensaje"]
    </span>
</h3>

<p>

</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dpi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nacimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dpi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nacimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
        </tr>
}
    </tbody>
</table>